# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d22d198cb517502491a8c3cf646a6d8d"
name = "drop-downie"
application_url = "https://drop-downie.vercel.app/"
embedded = true
handle = "drop-downie"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://drop-downie.vercel.app/auth/callback" ]

[pos]
embedded = false
